// frontend/src/components/analysis/AnalysisPanel.vue
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { getAnalysis, triggerAnalysis } from '../../api/analysis'
import type { VideoAnalysis, VideoUpload } from '../../types'
import { toast } from '../../composables/useToast'

const props = defineProps<{
  projectId: string
  upload: VideoUpload | null
}>()

const emit = defineEmits<{
  complete: [analysis: VideoAnalysis]
}>()

const analysis = ref<VideoAnalysis | null>(null)
const loading = ref(false)

async function load() {
  try {
    analysis.value = await getAnalysis(props.projectId)
  } catch {
    analysis.value = null
  }
}

async function analyze() {
  loading.value = true
  try {
    analysis.value = await triggerAnalysis(props.projectId)
    emit('complete', analysis.value)
    toast('success', '分析任务已完成')
  } catch {
    toast('error', '分析失败，请确认已上传视频')
  } finally {
    loading.value = false
  }
}

onMounted(load)
watch(() => props.projectId, load)
</script>

<template>
  <section class="mx-auto max-w-4xl p-6">
    <div class="mb-5 flex items-center justify-between gap-4">
      <div>
        <h2 class="text-xl font-semibold">视频分析</h2>
        <p class="mt-1 text-sm text-[#867351]">提取场景摘要、标签和推荐素材分类。</p>
      </div>
      <button
        type="button"
        class="rounded-lg bg-[#7e9d53] px-4 py-2 text-sm text-white hover:bg-[#718f47] disabled:opacity-50"
        :disabled="loading || !upload"
        @click="analyze"
      >
        {{ loading ? '分析中...' : '开始分析' }}
      </button>
    </div>

    <div v-if="!upload" class="rounded-lg border border-[#d7c7a8] bg-[#fff8ec] p-5 text-sm text-[#7b6847]">
      请先上传参考视频。
    </div>

    <article v-else-if="analysis" class="rounded-lg border border-[#d7c7a8] bg-white/85 p-5">
      <div class="mb-4 flex items-center justify-between">
        <span class="font-medium">状态：{{ analysis.status }}</span>
        <span class="text-xs text-[#8a7857]">{{ analysis.completed_at || analysis.created_at }}</span>
      </div>
      <p class="whitespace-pre-wrap text-sm leading-6">{{ analysis.summary || '暂无摘要' }}</p>
      <div v-if="analysis.scene_tags?.length" class="mt-5">
        <div class="mb-2 text-xs font-medium text-[#867351]">场景标签</div>
        <div class="flex flex-wrap gap-2">
          <span v-for="tag in analysis.scene_tags" :key="tag" class="rounded-full bg-[#f2e8d6] px-3 py-1 text-xs">{{ tag }}</span>
        </div>
      </div>
      <div v-if="analysis.recommended_categories?.length" class="mt-5">
        <div class="mb-2 text-xs font-medium text-[#867351]">推荐素材分类</div>
        <div class="flex flex-wrap gap-2">
          <span v-for="category in analysis.recommended_categories" :key="category" class="rounded-full bg-[#edf5de] px-3 py-1 text-xs text-[#526b32]">
            {{ category }}
          </span>
        </div>
      </div>
      <p v-if="analysis.error_message" class="mt-4 rounded-lg bg-[#fff1ec] p-3 text-sm text-[#8a3a2b]">
        {{ analysis.error_message }}
      </p>
    </article>

    <div v-else class="rounded-lg border border-[#d7c7a8] bg-[#fff8ec] p-5 text-sm text-[#7b6847]">
      暂无分析记录。
    </div>
  </section>
</template>

// frontend/src/components/analysis/AnalysisPanel.tsx
import { useState, useEffect } from 'react'
import { Brain, Loader2, AlertCircle, Tag, FolderOpen } from 'lucide-react'
import { triggerAnalysis, getAnalysis } from '../../api/analysis'
import { getVideoStreamUrl } from '../../api/upload'
import { getUpload } from '../../api/upload'
import type { VideoAnalysis, VideoUpload } from '../../types'

interface Props {
  projectId: string
  upload: VideoUpload | null
  onComplete: (analysis: VideoAnalysis) => void
}

export default function AnalysisPanel({ projectId, upload, onComplete }: Props) {
  const [analysis, setAnalysis] = useState<VideoAnalysis | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    getAnalysis(projectId).then(setAnalysis).catch(() => {})
  }, [projectId])

  useEffect(() => {
    if (!analysis || (analysis.status !== 'pending' && analysis.status !== 'processing')) return
    const timer = setInterval(async () => {
      const updated = await getAnalysis(projectId)
      setAnalysis(updated)
      if (updated.status === 'completed') {
        onComplete(updated)
        clearInterval(timer)
      } else if (updated.status === 'failed') {
        clearInterval(timer)
      }
    }, 2000)
    return () => clearInterval(timer)
  }, [analysis?.status, projectId, onComplete])

  const handleStart = async () => {
    setLoading(true)
    setError('')
    try {
      const result = await triggerAnalysis(projectId)
      setAnalysis(result)
    } catch (e: any) {
      setError(e.response?.data?.detail || '分析启动失败')
    } finally {
      setLoading(false)
    }
  }

  const isProcessing = analysis?.status === 'pending' || analysis?.status === 'processing'
  const hasResult = analysis?.status === 'completed' || analysis?.status === 'failed'

  return (
    <div className="flex h-full">
      {/* Left: Video preview */}
      <div className="w-1/2 border-r border-gray-200 flex flex-col">
        <div className="p-4 border-b border-gray-200">
          <h3 className="text-sm font-medium text-gray-700">上传的视频</h3>
        </div>
        <div className="flex-1 flex items-center justify-center bg-gray-50 p-4">
          {upload ? (
            <video
              src={getVideoStreamUrl(upload.id)}
              controls
              className="w-full max-h-full rounded-lg"
            />
          ) : (
            <p className="text-gray-400 text-sm">请先在上一步上传视频</p>
          )}
        </div>
      </div>

      {/* Right: Analysis results */}
      <div className="w-1/2 overflow-y-auto">
        <div className="p-6">
          {!analysis && (
            <div className="text-center py-12">
              <Brain className="mx-auto text-gray-400 mb-4" size={56} />
              <h2 className="text-lg text-gray-900 mb-2">AI 视频理解</h2>
              <p className="text-gray-500 mb-6 text-sm">使用 AI 分析视频内容，自动识别场景类型并推荐素材分类</p>
              <button
                onClick={handleStart}
                disabled={loading}
                className="px-6 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg transition-colors disabled:opacity-50 flex items-center gap-2 mx-auto text-sm"
              >
                {loading ? <Loader2 className="animate-spin" size={16} /> : <Brain size={16} />}
                开始分析
              </button>
              {error && <p className="mt-4 text-red-500 flex items-center gap-2 justify-center text-sm"><AlertCircle size={14} />{error}</p>}
            </div>
          )}

          {isProcessing && (
            <div className="text-center py-12">
              <Loader2 className="mx-auto text-blue-500 animate-spin mb-4" size={48} />
              <h2 className="text-lg text-gray-900 mb-2">正在分析视频...</h2>
              <p className="text-gray-500 text-sm">AI 正在理解视频内容，请稍候</p>
            </div>
          )}

          {analysis?.status === 'completed' && (
            <div className="space-y-4">
              <div className="bg-gray-50 rounded-xl p-5 border border-gray-200">
                <h3 className="text-gray-900 font-medium mb-2 flex items-center gap-2 text-sm">
                  <Brain size={16} className="text-blue-600" />分析摘要
                </h3>
                <p className="text-gray-700 leading-relaxed text-sm">{analysis.summary}</p>
              </div>

              {analysis.scene_tags && (
                <div className="bg-gray-50 rounded-xl p-5 border border-gray-200">
                  <h3 className="text-gray-900 font-medium mb-2 flex items-center gap-2 text-sm">
                    <Tag size={16} className="text-blue-600" />场景标签
                  </h3>
                  <div className="flex flex-wrap gap-2">
                    {analysis.scene_tags.map((tag) => (
                      <span key={tag} className="px-3 py-1 bg-blue-50 text-blue-700 rounded-full text-xs border border-blue-200">{tag}</span>
                    ))}
                  </div>
                </div>
              )}

              {analysis.recommended_categories && (
                <div className="bg-gray-50 rounded-xl p-5 border border-gray-200">
                  <h3 className="text-gray-900 font-medium mb-2 flex items-center gap-2 text-sm">
                    <FolderOpen size={16} className="text-blue-600" />推荐素材分类
                  </h3>
                  <div className="flex flex-wrap gap-2">
                    {analysis.recommended_categories.map((cat) => (
                      <span key={cat} className="px-3 py-1 bg-green-50 text-green-700 rounded-lg text-xs border border-green-200">{cat}</span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {analysis?.status === 'failed' && (
            <div className="text-center py-12">
              <AlertCircle className="mx-auto text-red-400 mb-4" size={48} />
              <h2 className="text-lg text-gray-900 mb-2">分析失败</h2>
              <p className="text-red-500 text-sm">{analysis.error_message}</p>
              <button onClick={handleStart} className="mt-4 px-6 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm">
                重新分析
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
