// frontend/src/components/prompt/PromptWorkspace.vue
<script setup lang="ts">
import { nextTick, onMounted, ref, watch } from 'vue'
import {
  generatePrompts,
  getChatHistory,
  getPrompts,
  getTemplates,
  sendChatMessage,
  updatePrompt,
} from '../../api/prompts'
import { getSelectedMaterials } from '../../api/materials'
import type { ChatMessage, MaterialSelection, Prompt, PromptTemplate } from '../../types'
import { toast } from '../../composables/useToast'

const props = defineProps<{
  projectId: string
}>()

const templates = ref<PromptTemplate[]>([])
const messages = ref<ChatMessage[]>([])
const prompts = ref<Prompt[]>([])
const selections = ref<MaterialSelection[]>([])
const input = ref('')
const streamText = ref('')
const streaming = ref(false)
const generating = ref(false)
const editingId = ref<string | null>(null)
const editText = ref('')
const messagesEnd = ref<HTMLElement | null>(null)

async function refresh() {
  const [templateList, chatList, promptList, selectionList] = await Promise.all([
    getTemplates().catch(() => []),
    getChatHistory(props.projectId).catch(() => []),
    getPrompts(props.projectId).catch(() => []),
    getSelectedMaterials(props.projectId).catch(() => []),
  ])
  templates.value = templateList
  messages.value = chatList
  prompts.value = promptList
  selections.value = selectionList
  await scrollToBottom()
}

async function scrollToBottom() {
  await nextTick()
  messagesEnd.value?.scrollIntoView({ block: 'end' })
}

async function send() {
  const content = input.value.trim()
  if (!content || streaming.value) return

  input.value = ''
  streamText.value = ''
  streaming.value = true
  messages.value.push({
    id: `local-${Date.now()}`,
    role: 'user',
    content,
    created_at: new Date().toISOString(),
  })

  try {
    await sendChatMessage(props.projectId, content, (chunk) => {
      streamText.value += chunk
      scrollToBottom()
    })
    await refresh()
  } catch {
    toast('error', '发送消息失败')
  } finally {
    streaming.value = false
    streamText.value = ''
  }
}

async function makePrompts() {
  generating.value = true
  try {
    prompts.value = await generatePrompts(props.projectId)
    toast('success', '提示词已生成')
  } catch {
    toast('error', '生成提示词失败')
  } finally {
    generating.value = false
  }
}

function startEdit(prompt: Prompt) {
  editingId.value = prompt.id
  editText.value = prompt.prompt_text
}

async function saveEdit(prompt: Prompt) {
  try {
    const updated = await updatePrompt(props.projectId, prompt.id, editText.value)
    prompts.value = prompts.value.map((item) => (item.id === updated.id ? updated : item))
    editingId.value = null
    toast('success', '提示词已保存')
  } catch {
    toast('error', '保存失败')
  }
}

onMounted(refresh)
watch(() => props.projectId, refresh)
</script>

<template>
  <section class="grid h-full grid-cols-[minmax(0,1fr)_380px] overflow-hidden">
    <main class="flex min-h-0 flex-col border-r border-[#d8c9ad]">
      <div class="border-b border-[#d8c9ad] bg-[#fff8ec] px-6 py-4">
        <h2 class="text-lg font-semibold">提示词工作区</h2>
        <p class="text-sm text-[#867351]">和 agent 对话，整理脚本和镜头提示词。</p>
      </div>

      <div class="min-h-0 flex-1 space-y-3 overflow-auto p-6">
        <article
          v-for="message in messages"
          :key="message.id"
          class="max-w-3xl rounded-lg border p-4 text-sm leading-6"
          :class="message.role === 'user' ? 'ml-auto border-[#c7d9a3] bg-[#f4f8e9]' : 'border-[#d7c7a8] bg-white/85'"
        >
          <div class="mb-1 text-xs font-medium text-[#867351]">{{ message.role === 'user' ? '你' : 'assistant' }}</div>
          <p class="whitespace-pre-wrap">{{ message.content }}</p>
        </article>

        <article v-if="streaming" class="max-w-3xl rounded-lg border border-[#d7c7a8] bg-white/85 p-4 text-sm leading-6">
          <div class="mb-1 text-xs font-medium text-[#867351]">assistant</div>
          <p class="whitespace-pre-wrap">{{ streamText || '正在思考...' }}</p>
        </article>
        <div ref="messagesEnd" />
      </div>

      <form class="border-t border-[#d8c9ad] bg-[#fff9ef] p-4" @submit.prevent="send">
        <div class="flex gap-2">
          <textarea
            v-model="input"
            class="min-h-20 flex-1 resize-none rounded-lg border border-[#daccb3] bg-white px-4 py-3 text-sm outline-none focus:border-[#8ca65c]"
            placeholder="描述你想要的视频风格、产品卖点或要调整的脚本..."
            @keydown.enter.exact.prevent="send"
          />
          <button
            type="submit"
            class="w-24 rounded-lg bg-[#7e9d53] text-sm text-white hover:bg-[#718f47] disabled:opacity-50"
            :disabled="streaming || !input.trim()"
          >
            发送
          </button>
        </div>
      </form>
    </main>

    <aside class="min-h-0 overflow-auto bg-[#fff8ec] p-5">
      <div class="mb-5 flex items-center justify-between">
        <h3 class="font-semibold">镜头提示词</h3>
        <button
          type="button"
          class="rounded-lg bg-[#7e9d53] px-3 py-2 text-xs text-white hover:bg-[#718f47] disabled:opacity-50"
          :disabled="generating"
          @click="makePrompts"
        >
          {{ generating ? '生成中...' : '生成提示词' }}
        </button>
      </div>

      <div v-if="selections.length" class="mb-5 rounded-lg border border-[#d7c7a8] bg-white/75 p-3">
        <div class="mb-2 text-xs font-medium text-[#867351]">已选素材</div>
        <div class="flex flex-wrap gap-2">
          <span v-for="item in selections" :key="item.id" class="rounded-full bg-[#edf5de] px-2 py-1 text-xs text-[#526b32]">
            {{ item.material?.filename || item.category }}
          </span>
        </div>
      </div>

      <div v-if="templates.length" class="mb-5 rounded-lg border border-[#d7c7a8] bg-white/75 p-3">
        <div class="mb-2 text-xs font-medium text-[#867351]">模板</div>
        <div class="space-y-2">
          <button
            v-for="template in templates"
            :key="template.name"
            type="button"
            class="w-full rounded-lg border border-[#eadfca] bg-[#fffaf1] px-3 py-2 text-left text-xs hover:bg-[#f4ead8]"
            @click="input = template.template"
          >
            <div class="font-medium">{{ template.name }}</div>
            <div class="mt-1 text-[#8a7857]">{{ template.description }}</div>
          </button>
        </div>
      </div>

      <div class="space-y-3">
        <article v-for="prompt in prompts" :key="prompt.id" class="rounded-lg border border-[#d7c7a8] bg-white p-3">
          <textarea
            v-if="editingId === prompt.id"
            v-model="editText"
            class="min-h-36 w-full resize-y rounded-lg border border-[#daccb3] p-3 text-sm outline-none focus:border-[#8ca65c]"
          />
          <p v-else class="whitespace-pre-wrap text-sm leading-6">{{ prompt.prompt_text }}</p>
          <div class="mt-3 flex justify-end gap-2">
            <button
              v-if="editingId === prompt.id"
              type="button"
              class="rounded-lg bg-[#7e9d53] px-3 py-1.5 text-xs text-white"
              @click="saveEdit(prompt)"
            >
              保存
            </button>
            <button
              type="button"
              class="rounded-lg border border-[#d7c7a8] px-3 py-1.5 text-xs hover:bg-[#f4ead8]"
              @click="editingId === prompt.id ? editingId = null : startEdit(prompt)"
            >
              {{ editingId === prompt.id ? '取消' : '编辑' }}
            </button>
          </div>
        </article>
      </div>
    </aside>
  </section>
</template>

// frontend/src/components/prompt/PromptWorkspace.tsx
import { useState, useEffect, useRef } from 'react'
import { getTemplates, getChatHistory, sendChatMessage, generatePrompts, getPrompts, updatePrompt } from '../../api/prompts'
import { getSelectedMaterials } from '../../api/materials'
import type { PromptTemplate, ChatMessage, Prompt, MaterialSelection } from '../../types'
import { Send, Loader2, Wand2, Edit3, Check, MessageSquare, Image as ImageIcon, X } from 'lucide-react'
import { cn } from '../../lib/utils'

interface Props {
  projectId: string
}

export default function PromptWorkspace({ projectId }: Props) {
  const [templates, setTemplates] = useState<PromptTemplate[]>([])
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [prompts, setPrompts] = useState<Prompt[]>([])
  const [input, setInput] = useState('')
  const [streaming, setStreaming] = useState(false)
  const [streamText, setStreamText] = useState('')
  const [generating, setGenerating] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editText, setEditText] = useState('')
  const [selections, setSelections] = useState<MaterialSelection[]>([])
  const [attachedMaterials, setAttachedMaterials] = useState<MaterialSelection[]>([])
  const chatEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    getTemplates().then(setTemplates)
    getChatHistory(projectId).then(setMessages)
    getPrompts(projectId).then(setPrompts)
    getSelectedMaterials(projectId).then(setSelections)
  }, [projectId])

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, streamText])

  const handleSend = async () => {
    if ((!input.trim() && attachedMaterials.length === 0) || streaming) return

    let content = input.trim()
    if (attachedMaterials.length > 0) {
      const materialRefs = attachedMaterials.map((s) => {
        const name = s.material?.filename || '素材'
        const cat = s.category
        return `[素材: ${cat}/${name}]`
      }).join(' ')
      content = content ? `${materialRefs}\n${content}` : materialRefs
    }

    setInput('')
    setAttachedMaterials([])

    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content,
      created_at: new Date().toISOString(),
    }
    setMessages((prev) => [...prev, userMsg])

    setStreaming(true)
    setStreamText('')
    let collected = ''
    await sendChatMessage(projectId, content, (chunk) => {
      collected += chunk
      setStreamText(collected)
    })
    setMessages((prev) => [...prev, {
      id: (Date.now() + 1).toString(),
      role: 'assistant',
      content: collected,
      created_at: new Date().toISOString(),
    }])
    setStreamText('')
    setStreaming(false)
  }

  const handleGenerate = async () => {
    setGenerating(true)
    try {
      const result = await generatePrompts(projectId)
      setPrompts(result)
    } finally {
      setGenerating(false)
    }
  }

  const handleSaveEdit = async (promptId: string) => {
    await updatePrompt(projectId, promptId, editText)
    setPrompts((prev) => prev.map((p) => p.id === promptId ? { ...p, prompt_text: editText } : p))
    setEditingId(null)
  }

  const toggleAttachMaterial = (sel: MaterialSelection) => {
    setAttachedMaterials((prev) => {
      const exists = prev.some((s) => s.material_id === sel.material_id)
      if (exists) return prev.filter((s) => s.material_id !== sel.material_id)
      return [...prev, sel]
    })
  }

  const isAttached = (sel: MaterialSelection) =>
    attachedMaterials.some((s) => s.material_id === sel.material_id)

  const selectionsByCategory = selections.reduce<Record<string, MaterialSelection[]>>((acc, s) => {
    if (!acc[s.category]) acc[s.category] = []
    acc[s.category].push(s)
    return acc
  }, {})

  const renderMessageContent = (content: string) => {
    const materialRefRegex = /\[素材: ([^\]]+)\]/g
    const parts: (string | { ref: string })[] = []
    let lastIndex = 0
    let match
    while ((match = materialRefRegex.exec(content)) !== null) {
      if (match.index > lastIndex) {
        parts.push(content.slice(lastIndex, match.index))
      }
      parts.push({ ref: match[1] })
      lastIndex = match.index + match[0].length
    }
    if (lastIndex < content.length) {
      parts.push(content.slice(lastIndex))
    }

    return (
      <>
        {parts.map((part, i) =>
          typeof part === 'string' ? (
            <span key={i}>{part}</span>
          ) : (
            <span key={i} className="inline-flex items-center gap-1 px-1.5 py-0.5 bg-blue-50 rounded text-blue-600 text-xs mx-0.5">
              <ImageIcon size={10} />
              {part.ref}
            </span>
          )
        )}
      </>
    )
  }

  return (
    <div className="flex h-full">
      {/* Left: Selected materials panel */}
      <div className="w-56 bg-gray-50 border-r border-gray-200 overflow-y-auto shrink-0 flex flex-col">
        <div className="p-3 text-xs text-gray-400 uppercase tracking-wider">已选素材</div>

        {selections.length === 0 ? (
          <div className="flex-1 flex items-center justify-center text-gray-400 text-sm px-4 text-center">
            <p>暂无选中素材，请在上一步选择素材</p>
          </div>
        ) : (
          <div className="flex-1 overflow-y-auto">
            {Object.entries(selectionsByCategory).map(([category, sels]) => (
              <div key={category} className="mb-2">
                <div className="px-3 py-1.5 text-xs text-gray-500 font-medium">{category}</div>
                <div className="grid grid-cols-2 gap-1.5 px-2">
                  {sels.map((sel) => {
                    const mat = sel.material
                    const attached = isAttached(sel)
                    return (
                      <button
                        key={sel.material_id}
                        onClick={() => toggleAttachMaterial(sel)}
                        className={cn(
                          'relative rounded-lg overflow-hidden border-2 transition-all aspect-square',
                          attached
                            ? 'border-blue-500 ring-1 ring-blue-500/30'
                            : 'border-transparent hover:border-gray-300',
                        )}
                        title={mat?.filename || '素材'}
                      >
                        <img
                          src={mat?.thumbnail_url || ''}
                          alt={mat?.filename || ''}
                          className="w-full h-full object-cover"
                          loading="lazy"
                        />
                        {attached && (
                          <div className="absolute inset-0 bg-blue-500/20 flex items-center justify-center">
                            <Check size={16} className="text-white drop-shadow" />
                          </div>
                        )}
                      </button>
                    )
                  })}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Templates section */}
        <div className="border-t border-gray-200">
          <div className="p-3 text-xs text-gray-400 uppercase tracking-wider">模板</div>
          {templates.map((t) => (
            <button
              key={t.name}
              onClick={() => setInput(t.template)}
              className="w-full text-left px-3 py-2 border-b border-gray-100 hover:bg-gray-100 transition-colors"
            >
              <div className="text-xs text-gray-900 font-medium">{t.name}</div>
              <div className="text-[11px] text-gray-400 mt-0.5">{t.description}</div>
            </button>
          ))}

          <div className="p-3">
            <button
              onClick={handleGenerate}
              disabled={generating || selections.length === 0}
              className="w-full px-4 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-sm flex items-center justify-center gap-2 disabled:opacity-50"
            >
              {generating ? <Loader2 className="animate-spin" size={16} /> : <Wand2 size={16} />}
              生成提示词
            </button>
          </div>
        </div>
      </div>

      {/* Center: Chat */}
      <div className="flex-1 flex flex-col min-w-0">
        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {messages.length === 0 && !streaming && (
            <div className="text-center text-gray-400 mt-20">
              <MessageSquare size={48} className="mx-auto mb-3" />
              <p>点击左侧素材将其附加到消息中</p>
              <p className="text-sm mt-1">选择模板或直接输入需求，AI 将帮助您生成视频提示词</p>
            </div>
          )}
          {messages.map((msg) => (
            <div key={msg.id} className={cn('flex', msg.role === 'user' ? 'justify-end' : 'justify-start')}>
              <div className={cn(
                'max-w-[80%] rounded-xl px-4 py-2.5 text-sm whitespace-pre-wrap',
                msg.role === 'user' ? 'bg-blue-600 text-white' : 'bg-gray-100 text-gray-700',
              )}>
                {renderMessageContent(msg.content)}
              </div>
            </div>
          ))}
          {streaming && streamText && (
            <div className="flex justify-start">
              <div className="max-w-[80%] rounded-xl px-4 py-2.5 text-sm bg-gray-100 text-gray-700 whitespace-pre-wrap">
                {streamText}
                <span className="inline-block w-1.5 h-4 bg-blue-500 ml-0.5 animate-pulse" />
              </div>
            </div>
          )}
          <div ref={chatEndRef} />
        </div>

        {/* Attached materials preview */}
        {attachedMaterials.length > 0 && (
          <div className="px-4 py-2 border-t border-gray-200 flex items-center gap-2 flex-wrap">
            <span className="text-xs text-gray-400">附加素材:</span>
            {attachedMaterials.map((sel) => (
              <div
                key={sel.material_id}
                className="relative group inline-flex items-center gap-1 px-1.5 py-0.5 bg-blue-50 rounded text-xs text-blue-600"
              >
                <img
                  src={sel.material?.thumbnail_url || ''}
                  alt=""
                  className="w-5 h-5 rounded object-cover"
                />
                <span className="max-w-[80px] truncate">{sel.material?.filename || '素材'}</span>
                <button
                  onClick={() => toggleAttachMaterial(sel)}
                  className="ml-0.5 text-gray-400 hover:text-red-500"
                >
                  <X size={10} />
                </button>
              </div>
            ))}
          </div>
        )}

        {/* Input */}
        <div className="p-4 border-t border-gray-200">
          <div className="flex gap-2">
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && handleSend()}
              placeholder={attachedMaterials.length > 0 ? '描述想要的效果（可选）...' : '输入您的需求...'}
              className="flex-1 bg-gray-50 text-gray-900 rounded-lg px-4 py-2.5 text-sm border border-gray-300 focus:border-blue-500 focus:outline-none"
            />
            <button
              onClick={handleSend}
              disabled={(!input.trim() && attachedMaterials.length === 0) || streaming}
              className="px-4 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg disabled:opacity-50"
            >
              <Send size={18} />
            </button>
          </div>
        </div>
      </div>

      {/* Right: Bound cards (material + prompt) */}
      {prompts.length > 0 && (
        <div className="w-80 bg-gray-50 border-l border-gray-200 overflow-y-auto shrink-0">
          <div className="p-3 text-xs text-gray-400 uppercase tracking-wider">
            素材绑定 ({prompts.length})
          </div>
          <p className="px-3 pb-2 text-[11px] text-gray-400">每个素材已绑定一条提示词，可编辑后进入下一步生成视频</p>
          {prompts.map((p, i) => {
            const matchedSel = selections.find((s) => s.id === p.material_selection_id)
            return (
              <div key={p.id} className="mx-3 mb-3 bg-white rounded-lg overflow-hidden border border-gray-200">
                <div className="flex items-center gap-2 p-2 bg-gray-50">
                  {matchedSel?.material?.thumbnail_url ? (
                    <img
                      src={matchedSel.material.thumbnail_url}
                      alt=""
                      className="w-10 h-10 rounded object-cover"
                    />
                  ) : (
                    <div className="w-10 h-10 rounded bg-gray-200 flex items-center justify-center">
                      <ImageIcon size={16} className="text-gray-400" />
                    </div>
                  )}
                  <div className="min-w-0 flex-1">
                    <span className="text-xs text-blue-600 block">绑定 #{i + 1}</span>
                    {matchedSel && (
                      <span className="text-[11px] text-gray-400 truncate block">
                        {matchedSel.category} / {matchedSel.material?.filename}
                      </span>
                    )}
                  </div>
                  {editingId === p.id ? (
                    <button onClick={() => handleSaveEdit(p.id)} className="text-green-500 hover:text-green-600 p-1">
                      <Check size={14} />
                    </button>
                  ) : (
                    <button onClick={() => { setEditingId(p.id); setEditText(p.prompt_text) }} className="text-gray-400 hover:text-gray-700 p-1">
                      <Edit3 size={14} />
                    </button>
                  )}
                </div>
                <div className="p-2">
                  {editingId === p.id ? (
                    <textarea
                      value={editText}
                      onChange={(e) => setEditText(e.target.value)}
                      className="w-full bg-gray-50 text-gray-700 text-xs rounded p-2 border border-gray-300 focus:border-blue-500 focus:outline-none resize-none"
                      rows={4}
                      autoFocus
                    />
                  ) : (
                    <p className="text-xs text-gray-500 leading-relaxed">{p.prompt_text}</p>
                  )}
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
