// frontend/src/components/ui/CapyAvatar.vue
<script setup lang="ts">
defineProps<{
  size?: 'sm' | 'md' | 'lg'
  className?: string
}>()

const sizes = {
  sm: 'h-8 w-8',
  md: 'h-11 w-11',
  lg: 'h-20 w-20',
}
</script>

<template>
  <img
    src="/capy-avatar.svg"
    alt="capy"
    class="rounded-full border object-cover"
    :class="[sizes[size || 'md'], className]"
  >
</template>

// frontend/src/components/ui/CapyAvatar.tsx
import { cn } from '../../lib/utils'

interface Props {
  size?: 'sm' | 'md' | 'lg'
  className?: string
}

const SIZE_MAP: Record<NonNullable<Props['size']>, string> = {
  sm: 'h-8 w-8',
  md: 'h-10 w-10',
  lg: 'h-14 w-14',
}

export default function CapyAvatar({ size = 'md', className }: Props) {
  return (
    <img
      src="/capy-avatar.svg"
      alt="capy avatar"
      className={cn('rounded-2xl border border-slate-200 bg-white object-cover shadow-sm', SIZE_MAP[size], className)}
    />
  )
}
