// frontend/src/App.tsx
import { useState, useEffect, useCallback, useRef } from 'react'
import { useProjectStore } from './stores/projectStore'
import { usePipelineStore } from './stores/pipelineStore'
import { useToast } from './components/ui/Toast'
import { getMe, logout } from './api/auth'
import { createProject, listProjects, updateProject } from './api/projects'
import { getUpload } from './api/upload'
import { scanMaterials } from './api/materials'
import { getAnalysis } from './api/analysis'
import AppShell from './components/layout/AppShell'
import AuthPage from './components/auth/AuthPage'
import ExampleGallery from './components/layout/ExampleGallery'
import UsageDashboardPage from './components/dashboard/UsageDashboardPage'
import VideoUploader from './components/upload/VideoUploader'
import AnalysisPanel from './components/analysis/AnalysisPanel'
import MaterialBrowser from './components/materials/MaterialBrowser'
import PromptWorkspace from './components/prompt/PromptWorkspace'
import GenerationPanel from './components/generation/GenerationPanel'
import TimelineEditor from './components/timeline/TimelineEditor'
import AutoModeStudio from './components/pipeline/AutoModeStudio'
import RepositoryPage from './components/repository/RepositoryPage'
import type { AuthUser, Project, VideoUpload, VideoAnalysis } from './types'
import { Plus, FolderOpen, Wand2 } from 'lucide-react'
import CapyAvatar from './components/ui/CapyAvatar'

function ProjectList({ onSelect }: { onSelect: (p: Project) => void }) {
  const [projects, setProjects] = useState<Project[]>([])
  const [creating, setCreating] = useState(false)
  const [name, setName] = useState('')
  const { toast } = useToast()

  useEffect(() => {
    listProjects().then(setProjects).catch(() => toast('error', '加载项目列表失败'))
    scanMaterials().catch(() => {})  // scanning failure is non-critical
  }, [])

  const handleCreate = async () => {
    if (!name.trim()) return
    setCreating(true)
    const p = await createProject(name.trim())
    onSelect(p)
    setCreating(false)
  }

  return (
    <div className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(169,190,120,0.22),_transparent_30%),linear-gradient(180deg,#f8f0e1_0%,#eee2ca_100%)] flex items-center justify-center">
      <div className="max-w-lg w-full mx-4">
        <div className="text-center mb-8">
          <CapyAvatar size="lg" className="mx-auto mb-4 border-[#ccb98f] bg-[#faf1de]" />
          <h1 className="text-3xl font-bold text-[#4c3b22] mb-2">capy</h1>
          <p className="text-[#7b6847]">像卡皮巴拉一样稳定推进的视频工作台</p>
        </div>

        <div className="rounded-[28px] border border-[#d7c7a8] bg-white/82 p-6 mb-6 shadow-sm backdrop-blur">
          <h2 className="text-[#4c3b22] font-medium mb-4">创建新项目</h2>
          <div className="flex gap-2">
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleCreate()}
              placeholder="项目名称..."
              className="flex-1 rounded-2xl border border-[#daccb3] bg-[#fff8ec] px-4 py-2.5 text-sm text-[#4c3b22] focus:border-[#8ca65c] focus:outline-none"
            />
            <button
              onClick={handleCreate}
              disabled={!name.trim() || creating}
              className="px-4 py-2.5 bg-[#7e9d53] hover:bg-[#718f47] text-white rounded-2xl flex items-center gap-2 disabled:opacity-50"
            >
              <Plus size={18} />
              创建
            </button>
          </div>
        </div>

        {projects.length > 0 && (
          <div className="rounded-[28px] border border-[#d7c7a8] bg-white/82 p-6 shadow-sm backdrop-blur">
            <h2 className="text-[#4c3b22] font-medium mb-4">最近项目</h2>
            <div className="space-y-2">
              {projects.map((p) => (
                <button
                  key={p.id}
                  onClick={() => onSelect(p)}
                  className="w-full text-left px-4 py-3 bg-[#fff8ed] hover:bg-[#f7ecd7] rounded-2xl flex items-center justify-between transition-colors border border-[#e6dbc8]"
                >
                  <div>
                    <div className="text-[#4c3b22] text-sm">{p.name}</div>
                    <div className="text-xs text-[#8a7857]">步骤 {p.current_step}/7 | {new Date(p.created_at).toLocaleDateString()}</div>
                  </div>
                  <FolderOpen className="text-[#9a845d]" size={18} />
                </button>
              ))}
            </div>
          </div>
        )}

        <ExampleGallery />
      </div>
    </div>
  )
}

export default function App() {
  const { project, setProject, currentStep, setCurrentStep } = useProjectStore()
  const { isAutoMode, setAutoMode, reset: resetPipeline } = usePipelineStore()
  const { toast } = useToast()
  const openPickerFnRef = useRef<(() => void) | null>(null)
  const [authUser, setAuthUser] = useState<AuthUser | null>(null)
  const [authLoading, setAuthLoading] = useState(true)
  const [showDashboard, setShowDashboard] = useState(false)
  const [showRepository, setShowRepository] = useState(false)
  const [upload, setUpload] = useState<VideoUpload | null>(null)
  const [analysis, setAnalysis] = useState<VideoAnalysis | null>(null)
  const [maxStep, setMaxStep] = useState(1)

  useEffect(() => {
    getMe().then(setAuthUser).catch(() => setAuthUser(null)).finally(() => setAuthLoading(false))
  }, [])

  useEffect(() => {
    if (!project) return
    setMaxStep(Math.max(project.current_step, 1))
    getUpload(project.id).then(setUpload).catch(() => toast('warning', '加载上传记录失败'))
    getAnalysis(project.id).then(setAnalysis).catch(() => {})  // analysis may not exist yet
  }, [project])

  const goToStep = useCallback((step: number) => {
    setCurrentStep(step)
    if (project && step > maxStep) {
      setMaxStep(step)
      updateProject(project.id, { current_step: step })
    }
  }, [project, maxStep, setCurrentStep])

  const handleNext = useCallback(() => {
    goToStep(currentStep + 1)
  }, [currentStep, goToStep])

  const handleLogout = useCallback(async () => {
    try {
      await logout()
    } catch {}
    setAuthUser(null)
    setProject(null)
    resetPipeline()
    setShowDashboard(false)
    setShowRepository(false)
  }, [resetPipeline, setProject])

  const handleSwitchProject = useCallback((p: Project) => {
    setProject(p)
    setCurrentStep(p.current_step)
    setAutoMode(true)
    resetPipeline()
    setShowDashboard(false)
    setShowRepository(false)
  }, [setProject, setCurrentStep, setAutoMode, resetPipeline])

  if (authLoading) {
    return <div className="min-h-screen flex items-center justify-center text-[#7c6845]">加载登录状态中...</div>
  }

  if (!authUser) {
    return <AuthPage onAuthenticated={setAuthUser} />
  }

  if (!project) {
    return <ProjectList onSelect={(p) => { setProject(p); setCurrentStep(p.current_step); setAutoMode(true) }} />
  }

  return (
    <AppShell
      projectName={project.name}
      currentUserName={authUser.username}
      currentStep={isAutoMode ? 0 : currentStep}
      maxStep={Math.max(maxStep, currentStep)}
      onStepClick={isAutoMode ? undefined : goToStep}
      onOpenDashboard={() => { setShowDashboard(true); setShowRepository(false) }}
      onOpenRepository={() => { setShowRepository(true); setShowDashboard(false) }}
      onLogout={handleLogout}
      centerSlot={isAutoMode ? (
        <div className="flex items-center gap-2">
          <button className="rounded-full bg-[#7e9d53] text-white px-4 py-2 text-sm font-medium flex items-center gap-2">
            <Wand2 size={14} /> 一键生成
          </button>
          <button
            onClick={() => openPickerFnRef.current?.()}
            className="rounded-full bg-[#fffaf1] border border-[#d9ccb5] text-[#6d5936] px-4 py-2 text-sm font-medium hover:bg-[#f7ecd8] flex items-center gap-2"
          >
            <Plus size={14} /> 素材与视频
          </button>
          <button
            onClick={() => { setAutoMode(false); resetPipeline() }}
            className="rounded-full bg-[#fffaf1] border border-[#d9ccb5] text-[#6d5936] px-4 py-2 text-sm font-medium hover:bg-[#f7ecd8]"
          >
            手动模式
          </button>
        </div>
      ) : undefined}
    >
      <div className="h-full flex flex-col">
        <div className="flex-1 overflow-auto">
          {showRepository ? (
            <RepositoryPage onBack={() => setShowRepository(false)} />
          ) : showDashboard ? (
            <UsageDashboardPage
              currentProjectId={project.id}
              currentUser={authUser}
              onBack={() => setShowDashboard(false)}
            />
          ) : isAutoMode ? (
            <AutoModeStudio
              projectId={project.id}
              onSwitchToManual={() => { setAutoMode(false); resetPipeline() }}
              onSwitchProject={handleSwitchProject}
              onRegisterOpenPicker={(fn) => { openPickerFnRef.current = fn }}
            />
          ) : (
            /* ── Manual mode: Step-by-step workflow ── */
            <>
              <div className="px-6 py-3 border-b border-[#d8c9ad] bg-[#f8f0e1] flex items-center justify-between">
                <div>
                  <div className="text-sm font-medium text-[#4c3b22]">手动模式流水线</div>
                  <div className="text-xs text-[#867351] mt-0.5">逐步执行上传、分析、选素材、生成和剪辑</div>
                </div>
                <button
                  onClick={() => {
                    setAutoMode(true)
                    resetPipeline()
                  }}
                  className="px-4 py-2 text-sm rounded-2xl bg-[#fff8ec] border border-[#d7c7a8] text-[#6d5936] hover:bg-[#f5ebd7] transition-colors"
                >
                  返回一键生成
                </button>
              </div>
              {currentStep === 1 && (
                <VideoUploader
                  projectId={project.id}
                  upload={upload}
                  onUploaded={(u) => { setUpload(u); setMaxStep(Math.max(maxStep, 2)) }}
                />
              )}
              {currentStep === 2 && (
                <AnalysisPanel
                  projectId={project.id}
                  upload={upload}
                  onComplete={(a) => { setAnalysis(a); setMaxStep(Math.max(maxStep, 3)) }}
                />
              )}
              {currentStep === 3 && (
                <MaterialBrowser
                  projectId={project.id}
                  recommendedCategories={analysis?.recommended_categories || undefined}
                />
              )}
              {currentStep === 4 && (
                <PromptWorkspace projectId={project.id} />
              )}
              {(currentStep === 5 || currentStep === 6) && (
                <GenerationPanel projectId={project.id} />
              )}
              {currentStep === 7 && (
                <TimelineEditor projectId={project.id} />
              )}
            </>
          )}
        </div>

        {/* Step navigation — only in manual mode */}
        {!isAutoMode && !showDashboard && !showRepository && (
          <div className="flex items-center justify-between px-6 py-3 bg-[#fff9ef] border-t border-[#d8c9ad]">
            <button
              onClick={() => currentStep === 1 ? setProject(null) : goToStep(currentStep - 1)}
              className="px-4 py-2 text-sm text-[#6f5b38] hover:text-[#4c3b22] bg-[#f2e8d6] hover:bg-[#e8dcc4] rounded-2xl transition-colors"
            >
              {currentStep === 1 ? '返回项目列表' : '上一步'}
            </button>
            {currentStep < 7 && (
              <button
                onClick={handleNext}
                className="px-6 py-2 text-sm bg-[#7e9d53] hover:bg-[#718f47] text-white rounded-2xl transition-colors"
              >
                下一步
              </button>
            )}
          </div>
        )}
      </div>
    </AppShell>
  )
}

// frontend/src/App.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { getMe, logout } from './api/auth'
import { createProject, listProjects, updateProject } from './api/projects'
import { getUpload } from './api/upload'
import { getAnalysis } from './api/analysis'
import { scanMaterials } from './api/materials'
import { projectStore, setCurrentStep, setProject } from './stores/projectStore'
import { pipelineStore, resetPipeline, setAutoMode } from './stores/pipelineStore'
import type {
  AuthUser,
  MaterialItem,
  Project,
  RepositoryDelivery,
  RepositoryUpload,
  VideoAnalysis,
  VideoUpload,
} from './types'
import { toast } from './composables/useToast'
import ToastHost from './components/ui/ToastHost.vue'
import CapyAvatar from './components/ui/CapyAvatar.vue'
import AppShell from './components/layout/AppShell.vue'
import ExampleGallery from './components/layout/ExampleGallery.vue'
import AuthPage from './components/auth/AuthPage.vue'
import VideoUploader from './components/upload/VideoUploader.vue'
import AnalysisPanel from './components/analysis/AnalysisPanel.vue'
import MaterialBrowser from './components/materials/MaterialBrowser.vue'
import PromptWorkspace from './components/prompt/PromptWorkspace.vue'
import GenerationPanel from './components/generation/GenerationPanel.vue'
import TimelineEditor from './components/timeline/TimelineEditor.vue'
import AutoModeStudio from './components/pipeline/AutoModeStudio.vue'
import RepositoryPage from './components/repository/RepositoryPage.vue'
import UsageDashboardPage from './components/dashboard/UsageDashboardPage.vue'

type AutoModeStudioExpose = {
  handleRepositoryPicked: (
    items: MaterialItem[],
    upload: RepositoryUpload | null,
    delivery: RepositoryDelivery | null,
  ) => Promise<void>
}

const authUser = ref<AuthUser | null>(null)
const authLoading = ref(true)
const projects = ref<Project[]>([])
const creatingProject = ref(false)
const projectName = ref('')
const showDashboard = ref(false)
const showRepository = ref(false)
const repositoryPickerMode = ref(false)
const upload = ref<VideoUpload | null>(null)
const analysis = ref<VideoAnalysis | null>(null)
const maxStep = ref(1)
const autoModeStudio = ref<AutoModeStudioExpose | null>(null)

const project = computed(() => projectStore.project)
const currentStep = computed(() => projectStore.currentStep)
const isAutoMode = computed(() => pipelineStore.isAutoMode)

async function loadAuth() {
  try {
    authUser.value = await getMe()
    await loadProjects()
  } catch {
    authUser.value = null
  } finally {
    authLoading.value = false
  }
}

async function loadProjects() {
  projects.value = await listProjects().catch(() => [])
  scanMaterials().catch(() => undefined)
}

async function createNewProject() {
  const name = projectName.value.trim()
  if (!name || creatingProject.value) return

  creatingProject.value = true
  try {
    const created = await createProject(name)
    projects.value.unshift(created)
    selectProject(created)
    projectName.value = ''
  } catch {
    toast('error', '创建项目失败')
  } finally {
    creatingProject.value = false
  }
}

function selectProject(nextProject: Project) {
  setProject(nextProject)
  setCurrentStep(nextProject.current_step)
  setAutoMode(true)
  resetPipeline()
  showDashboard.value = false
  showRepository.value = false
  repositoryPickerMode.value = false
}

async function loadProjectData() {
  if (!project.value) return
  maxStep.value = Math.max(project.value.current_step, 1)
  upload.value = await getUpload(project.value.id).catch(() => null)
  analysis.value = await getAnalysis(project.value.id).catch(() => null)
}

function goToStep(step: number) {
  if (!project.value) return
  setCurrentStep(step)
  if (step > maxStep.value) {
    maxStep.value = step
    updateProject(project.value.id, { current_step: step }).catch(() => undefined)
  }
}

function handleNext() {
  goToStep(currentStep.value + 1)
}

async function handleLogout() {
  try {
    await logout()
  } catch {
    // The local session state still needs clearing even if the backend cookie is gone.
  }
  authUser.value = null
  setProject(null)
  resetPipeline()
  showDashboard.value = false
  showRepository.value = false
  repositoryPickerMode.value = false
}

function openRepository(pickerMode = false) {
  repositoryPickerMode.value = pickerMode
  showRepository.value = true
  showDashboard.value = false
}

async function handleRepositoryConfirm(
  items: MaterialItem[],
  selectedUpload: RepositoryUpload | null,
  selectedDelivery: RepositoryDelivery | null,
) {
  await autoModeStudio.value?.handleRepositoryPicked(items, selectedUpload, selectedDelivery)
  showRepository.value = false
  repositoryPickerMode.value = false
}

function backFromRepository() {
  showRepository.value = false
  repositoryPickerMode.value = false
}

function switchToManual(step = 7) {
  setAutoMode(false)
  resetPipeline()
  goToStep(step)
}

function switchToAuto() {
  setAutoMode(true)
  resetPipeline()
}

onMounted(loadAuth)
watch(project, loadProjectData)
</script>

<template>
  <ToastHost />

  <div v-if="authLoading" class="flex min-h-screen items-center justify-center text-[#7c6845]">
    加载登录状态中...
  </div>

  <AuthPage v-else-if="!authUser" @authenticated="authUser = $event; loadProjects()" />

  <section
    v-else-if="!project"
    class="flex min-h-screen items-center justify-center bg-[radial-gradient(circle_at_top,_rgba(169,190,120,0.22),_transparent_30%),linear-gradient(180deg,#f8f0e1_0%,#eee2ca_100%)] px-4"
  >
    <div class="w-full max-w-lg">
      <div class="mb-8 text-center">
        <CapyAvatar size="lg" className="mx-auto mb-4 border-[#ccb98f] bg-[#faf1de]" />
        <h1 class="mb-2 text-3xl font-bold text-[#4c3b22]">capy</h1>
        <p class="text-[#7b6847]">像卡皮巴拉一样稳定推进的视频工作台</p>
      </div>

      <form class="mb-6 rounded-lg border border-[#d7c7a8] bg-white/82 p-6 shadow-sm backdrop-blur" @submit.prevent="createNewProject">
        <h2 class="mb-4 font-medium text-[#4c3b22]">创建新项目</h2>
        <div class="flex gap-2">
          <input
            v-model="projectName"
            class="flex-1 rounded-lg border border-[#daccb3] bg-[#fff8ec] px-4 py-2.5 text-sm text-[#4c3b22] outline-none focus:border-[#8ca65c]"
            placeholder="项目名称..."
          >
          <button
            type="submit"
            class="rounded-lg bg-[#7e9d53] px-4 py-2.5 text-sm text-white hover:bg-[#718f47] disabled:opacity-50"
            :disabled="!projectName.trim() || creatingProject"
          >
            {{ creatingProject ? '创建中' : '创建' }}
          </button>
        </div>
      </form>

      <div v-if="projects.length > 0" class="rounded-lg border border-[#d7c7a8] bg-white/82 p-6 shadow-sm backdrop-blur">
        <h2 class="mb-4 font-medium text-[#4c3b22]">最近项目</h2>
        <div class="space-y-2">
          <button
            v-for="item in projects"
            :key="item.id"
            type="button"
            class="flex w-full items-center justify-between rounded-lg border border-[#e6dbc8] bg-[#fff8ed] px-4 py-3 text-left transition-colors hover:bg-[#f7ecd7]"
            @click="selectProject(item)"
          >
            <div>
              <div class="text-sm text-[#4c3b22]">{{ item.name }}</div>
              <div class="text-xs text-[#8a7857]">步骤 {{ item.current_step }}/7 · {{ new Date(item.created_at).toLocaleDateString() }}</div>
            </div>
            <span class="text-[#9a845d]">打开</span>
          </button>
        </div>
      </div>

      <ExampleGallery />
    </div>
  </section>

  <AppShell
    v-else
    :project-name="project.name"
    :current-user-name="authUser.username"
    :current-step="isAutoMode ? 0 : currentStep"
    :max-step="Math.max(maxStep, currentStep)"
    :auto-mode="isAutoMode"
    @step-click="goToStep"
    @open-dashboard="showDashboard = true; showRepository = false"
    @open-repository="openRepository(false)"
    @logout="handleLogout"
  >
    <template #center>
      <div v-if="isAutoMode" class="flex items-center gap-2">
        <button type="button" class="rounded-lg bg-[#7e9d53] px-4 py-2 text-sm font-medium text-white">
          一键生成
        </button>
        <button
          type="button"
          class="rounded-lg border border-[#d9ccb5] bg-[#fffaf1] px-4 py-2 text-sm font-medium text-[#6d5936] hover:bg-[#f7ecd8]"
          @click="switchToManual(7)"
        >
          手动模式
        </button>
      </div>
    </template>

    <div class="flex h-full flex-col">
      <div class="min-h-0 flex-1 overflow-hidden">
        <RepositoryPage
          v-if="showRepository"
          :picker-mode="repositoryPickerMode"
          @back="backFromRepository"
          @picker-confirm="handleRepositoryConfirm"
        />
        <UsageDashboardPage
          v-else-if="showDashboard"
          :current-project-id="project.id"
          :current-user="authUser"
          @back="showDashboard = false"
        />
        <AutoModeStudio
          v-show="isAutoMode && !showDashboard && !showRepository"
          ref="autoModeStudio"
          :project-id="project.id"
          @switch-to-manual="switchToManual(7)"
          @switch-project="selectProject"
          @open-repository-picker="openRepository(true)"
        />
        <template v-if="!isAutoMode && !showRepository && !showDashboard">
          <div class="flex items-center justify-between border-b border-[#d8c9ad] bg-[#f8f0e1] px-6 py-3">
            <div>
              <div class="text-sm font-medium text-[#4c3b22]">手动模式流水线</div>
              <div class="mt-0.5 text-xs text-[#867351]">逐步执行上传、分析、选素材、生成和剪辑</div>
            </div>
            <button
              type="button"
              class="rounded-lg border border-[#d7c7a8] bg-[#fff8ec] px-4 py-2 text-sm text-[#6d5936] transition-colors hover:bg-[#f5ebd7]"
              @click="switchToAuto"
            >
              返回一键生成
            </button>
          </div>
          <VideoUploader
            v-if="currentStep === 1"
            :project-id="project.id"
            :upload="upload"
            @uploaded="upload = $event; maxStep = Math.max(maxStep, 2)"
          />
          <AnalysisPanel
            v-else-if="currentStep === 2"
            :project-id="project.id"
            :upload="upload"
            @complete="analysis = $event; maxStep = Math.max(maxStep, 3)"
          />
          <MaterialBrowser
            v-else-if="currentStep === 3"
            :project-id="project.id"
            :recommended-categories="analysis?.recommended_categories || undefined"
          />
          <PromptWorkspace v-else-if="currentStep === 4" :project-id="project.id" />
          <GenerationPanel v-else-if="currentStep === 5 || currentStep === 6" :project-id="project.id" />
          <TimelineEditor v-else-if="currentStep === 7" :project-id="project.id" />
        </template>
      </div>

      <div v-if="!isAutoMode && !showDashboard && !showRepository" class="flex items-center justify-between border-t border-[#d8c9ad] bg-[#fff9ef] px-6 py-3">
        <button
          type="button"
          class="rounded-lg bg-[#f2e8d6] px-4 py-2 text-sm text-[#6f5b38] transition-colors hover:bg-[#e8dcc4] hover:text-[#4c3b22]"
          @click="currentStep === 1 ? setProject(null) : goToStep(currentStep - 1)"
        >
          {{ currentStep === 1 ? '返回项目列表' : '上一步' }}
        </button>
        <button
          v-if="currentStep < 7"
          type="button"
          class="rounded-lg bg-[#7e9d53] px-6 py-2 text-sm text-white transition-colors hover:bg-[#718f47]"
          @click="handleNext"
        >
          下一步
        </button>
      </div>
    </div>
  </AppShell>
</template>
